

const reports = [
    {
        "id": 1,
        "date" : "7 Jan 2021",
        "category": "Accessories",
        "sales": "$42",
        "refunded": "$0",
        "discounts": "$163",
        "taxr": "$221",
        "amount": "$762",
        "income": "Service Rendered",
        "income_amount": "$90000",
        "expense": "Salaries",
        "expense_amount": "$20000",
        "net_profit": "$70000",
        "gross_revenue": "$108",
        "net_revenue": "$108",
        "tax_rate": "5%",
        "tax": "Tax Free",
        "economic_zone": "Tax Free Customers",
    },
    {
        "id": 2,
        "date" : "28 Feb 2021",
        "category": "Books",
        "sales": "$1249",
        "refunded": "$36",
        "discounts": "$3",
        "taxr": "$80",
        "amount": "$1238",
        "income": "Service Rendered",
        "income_amount": "$50000",
        "expense": "Salaries",
        "expense_amount": "$10000",
        "net_profit": "$40000",
        "gross_revenue": "$608",
        "net_revenue": "$3660",
        "tax_rate": "6%",
        "tax": "General Sales Tax",
        "economic_zone": "Default",
    },
    {
        "id": 3,
        "date" : "10 Mar 2021",
        "category": "Others",
        "sales": "$76",
        "refunded": "$0",
        "discounts": "$0",
        "taxr": "$4",
        "amount": "$80",
        "income": "Service Rendered",
        "income_amount": "$50000",
        "expense": "Salaries",
        "expense_amount": "$10000",
        "net_profit": "$40000",
        "gross_revenue": "$508",
        "net_revenue": "$4660",
        "tax_rate": "7%",
        "tax": "General Sales Tax",
        "economic_zone": "Default",
    },
]

export default reports;